-- =====================================================================
-- V1: Initial schema for AI Disaster Management System
-- Column lengths aligned with JPA entity definitions (Hibernate validate)
-- Works on both H2 (PostgreSQL compatibility mode) and PostgreSQL 10+
-- =====================================================================

CREATE TABLE users (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username           VARCHAR(255) NOT NULL,
    email              VARCHAR(255) NOT NULL,
    password           VARCHAR(255) NOT NULL,
    role               VARCHAR(255) NOT NULL,
    phone              VARCHAR(255),
    address            VARCHAR(500),
    profile_photo      VARCHAR(255),
    emergency_contact  VARCHAR(255),
    active             BOOLEAN      NOT NULL DEFAULT TRUE,
    email_verified     BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login         TIMESTAMP,
    total_reports      INT          NOT NULL DEFAULT 0,
    assigned_disasters INT          NOT NULL DEFAULT 0,
    created_at         TIMESTAMP,
    updated_at         TIMESTAMP,
    version            BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE disasters (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disaster_type VARCHAR(255) NOT NULL,
    description   VARCHAR(1000),
    severity      VARCHAR(255) NOT NULL,
    location      VARCHAR(255) NOT NULL,
    latitude      DOUBLE PRECISION NOT NULL DEFAULT 0,
    longitude     DOUBLE PRECISION NOT NULL DEFAULT 0,
    date          TIMESTAMP NOT NULL,
    status        VARCHAR(255) NOT NULL,
    user_id       BIGINT,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    version       BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_disasters_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE hospitals (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255),
    available_beds    INT NOT NULL DEFAULT 0,
    icu_beds          INT NOT NULL DEFAULT 0,
    doctors_available INT NOT NULL DEFAULT 0,
    emergency_contact VARCHAR(255),
    blood_bank        BOOLEAN NOT NULL DEFAULT FALSE,
    latitude          DOUBLE PRECISION NOT NULL DEFAULT 0,
    longitude         DOUBLE PRECISION NOT NULL DEFAULT 0,
    address           VARCHAR(255)
);

CREATE TABLE shelters (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255),
    capacity        INT NOT NULL DEFAULT 0,
    occupancy       INT NOT NULL DEFAULT 0,
    food_available  BOOLEAN NOT NULL DEFAULT FALSE,
    water_available BOOLEAN NOT NULL DEFAULT FALSE,
    medical_kits    INT NOT NULL DEFAULT 0,
    power_available BOOLEAN NOT NULL DEFAULT FALSE,
    contact         VARCHAR(255),
    latitude        DOUBLE PRECISION NOT NULL DEFAULT 0,
    longitude       DOUBLE PRECISION NOT NULL DEFAULT 0,
    address         VARCHAR(255)
);

CREATE TABLE volunteers (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(255),
    email               VARCHAR(255),
    phone               VARCHAR(255),
    skills              VARCHAR(255),
    available           BOOLEAN NOT NULL DEFAULT TRUE,
    attended            BOOLEAN NOT NULL DEFAULT FALSE,
    latitude            DOUBLE PRECISION NOT NULL DEFAULT 0,
    longitude           DOUBLE PRECISION NOT NULL DEFAULT 0,
    assigned_disaster_id BIGINT,
    CONSTRAINT fk_volunteers_disaster FOREIGN KEY (assigned_disaster_id) REFERENCES disasters (id)
);

CREATE TABLE resources (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_type        VARCHAR(255),
    quantity             INT NOT NULL DEFAULT 0,
    available            BOOLEAN NOT NULL DEFAULT TRUE,
    location             VARCHAR(255),
    latitude             DOUBLE PRECISION NOT NULL DEFAULT 0,
    longitude            DOUBLE PRECISION NOT NULL DEFAULT 0,
    assigned_disaster_id BIGINT,
    CONSTRAINT fk_resources_disaster FOREIGN KEY (assigned_disaster_id) REFERENCES disasters (id)
);

CREATE TABLE drones (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drone_id             VARCHAR(255),
    status               VARCHAR(255),
    battery              INT NOT NULL DEFAULT 100,
    camera_status        BOOLEAN NOT NULL DEFAULT TRUE,
    latitude             DOUBLE PRECISION NOT NULL DEFAULT 0,
    longitude            DOUBLE PRECISION NOT NULL DEFAULT 0,
    mission_status       VARCHAR(255),
    assigned_disaster_id BIGINT,
    CONSTRAINT fk_drones_disaster FOREIGN KEY (assigned_disaster_id) REFERENCES disasters (id)
);

CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255),
    message    VARCHAR(1000),
    type       VARCHAR(255),
    is_read    BOOLEAN NOT NULL DEFAULT FALSE,
    user_id    BIGINT,
    created_at TIMESTAMP,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE audit_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action       VARCHAR(255),
    entity_type  VARCHAR(255),
    entity_id    BIGINT,
    performed_by VARCHAR(255),
    details      VARCHAR(255),
    timestamp    TIMESTAMP
);

CREATE TABLE system_settings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key   VARCHAR(255) NOT NULL,
    setting_value VARCHAR(1000),
    description   VARCHAR(255),
    CONSTRAINT uk_system_settings_key UNIQUE (setting_key)
);

CREATE TABLE case_studies (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               VARCHAR(255),
    disaster_type       VARCHAR(255),
    location            VARCHAR(255),
    disaster_year       INT,
    severity            VARCHAR(255),
    description         VARCHAR(255),
    lessons_learned     VARCHAR(2000),
    estimated_damage    DOUBLE PRECISION NOT NULL DEFAULT 0,
    affected_population INT NOT NULL DEFAULT 0,
    resources_used      DOUBLE PRECISION NOT NULL DEFAULT 0,
    response_time_hours DOUBLE PRECISION NOT NULL DEFAULT 0,
    recovery_time_days  DOUBLE PRECISION NOT NULL DEFAULT 0,
    recommendations     VARCHAR(255),
    created_at          TIMESTAMP
);

CREATE TABLE rescue_teams (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_name            VARCHAR(255),
    team_leader          VARCHAR(255),
    members              VARCHAR(255),
    vehicles             VARCHAR(255),
    equipment            VARCHAR(255),
    status               VARCHAR(255),
    location             VARCHAR(255),
    latitude             DOUBLE PRECISION NOT NULL DEFAULT 0,
    longitude            DOUBLE PRECISION NOT NULL DEFAULT 0,
    contact_number       VARCHAR(255),
    member_count         INT NOT NULL DEFAULT 0,
    assigned_disaster_id BIGINT,
    deployed_at          TIMESTAMP,
    returned_at          TIMESTAMP,
    version              BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_rescue_teams_disaster FOREIGN KEY (assigned_disaster_id) REFERENCES disasters (id)
);

CREATE TABLE team_members (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255),
    role       VARCHAR(255),
    speciality VARCHAR(255),
    phone      VARCHAR(255),
    available  BOOLEAN NOT NULL DEFAULT TRUE,
    team_id    BIGINT,
    CONSTRAINT fk_team_members_team FOREIGN KEY (team_id) REFERENCES rescue_teams (id)
);

CREATE TABLE status_timeline (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disaster_id   BIGINT,
    from_status   VARCHAR(255),
    to_status     VARCHAR(255),
    changed_at    TIMESTAMP,
    changed_by_id BIGINT,
    comment       VARCHAR(255),
    CONSTRAINT fk_timeline_disaster FOREIGN KEY (disaster_id) REFERENCES disasters (id),
    CONSTRAINT fk_timeline_user FOREIGN KEY (changed_by_id) REFERENCES users (id)
);

CREATE TABLE verification_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(255) NOT NULL,
    user_id     BIGINT NOT NULL,
    type        VARCHAR(50) NOT NULL,
    expiry_time TIMESTAMP NOT NULL,
    used        BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP NOT NULL,
    CONSTRAINT uk_verification_token UNIQUE (token),
    CONSTRAINT fk_verification_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(255) NOT NULL,
    user_id     BIGINT NOT NULL,
    expiry_time TIMESTAMP NOT NULL,
    revoked     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP NOT NULL,
    CONSTRAINT uk_refresh_token UNIQUE (token),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- =====================================================================
-- Indexes for hot query paths
-- =====================================================================
CREATE INDEX idx_disasters_date ON disasters (date DESC);
CREATE INDEX idx_disasters_user ON disasters (user_id);
CREATE INDEX idx_disasters_status ON disasters (status);
CREATE INDEX idx_notifications_user_read ON notifications (user_id, is_read);
CREATE INDEX idx_notifications_created ON notifications (created_at DESC);
CREATE INDEX idx_audit_logs_timestamp ON audit_logs (timestamp DESC);
CREATE INDEX idx_audit_logs_user ON audit_logs (performed_by);
CREATE INDEX idx_timeline_disaster ON status_timeline (disaster_id);
CREATE INDEX idx_users_active ON users (active);
CREATE INDEX idx_users_username ON users (username);
CREATE INDEX idx_rescue_teams_disaster ON rescue_teams (assigned_disaster_id);
CREATE INDEX idx_resources_type ON resources (resource_type);
CREATE INDEX idx_resources_disaster ON resources (assigned_disaster_id);
CREATE INDEX idx_volunteers_disaster ON volunteers (assigned_disaster_id);
CREATE INDEX idx_drones_disaster ON drones (assigned_disaster_id);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);
CREATE INDEX idx_verification_tokens_user ON verification_tokens (user_id);
