-- =====================================================================
-- V3: Disaster module enrichment
-- Adds priority + PDF attachments to disasters, plus comment and rescue
-- assignment history tables. Aligned with JPA entities (Hibernate validate).
-- Safe on both H2 (PostgreSQL mode) and PostgreSQL.
-- =====================================================================

ALTER TABLE disasters ADD COLUMN priority VARCHAR(20);
ALTER TABLE disasters ADD COLUMN pdf_urls VARCHAR(10000);

CREATE TABLE disaster_comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disaster_id BIGINT,
    author_id   BIGINT,
    text        VARCHAR(1000),
    created_at  TIMESTAMP,
    CONSTRAINT fk_comments_disaster FOREIGN KEY (disaster_id) REFERENCES disasters (id),
    CONSTRAINT fk_comments_author   FOREIGN KEY (author_id)   REFERENCES users (id)
);

CREATE TABLE disaster_assignments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disaster_id  BIGINT,
    team_id      BIGINT,
    team_name    VARCHAR(255),
    assigned_by  VARCHAR(255),
    assigned_at  TIMESTAMP,
    released_at  TIMESTAMP,
    action       VARCHAR(20) DEFAULT 'ASSIGNED',
    CONSTRAINT fk_assignments_disaster FOREIGN KEY (disaster_id) REFERENCES disasters (id),
    CONSTRAINT fk_assignments_team     FOREIGN KEY (team_id)     REFERENCES rescue_teams (id)
);

CREATE INDEX idx_comments_disaster ON disaster_comments (disaster_id);
CREATE INDEX idx_assignments_disaster ON disaster_assignments (disaster_id);
