-- =====================================================================
-- V4: Disaster attachments
-- Adds the disaster_attachments table that stores report evidence files
-- (images, videos, PDFs) as base64 data URLs. Aligned with the
-- DisasterAttachment JPA entity (Hibernate validate).
-- Safe on both H2 (PostgreSQL mode) and PostgreSQL.
-- =====================================================================

CREATE TABLE disaster_attachments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disaster_id BIGINT,
    category    VARCHAR(20),
    filename    VARCHAR(255),
    mime_type   VARCHAR(100),
    size        BIGINT,
    data_url    TEXT,
    created_at  TIMESTAMP,
    CONSTRAINT fk_attachments_disaster FOREIGN KEY (disaster_id) REFERENCES disasters (id)
);

CREATE INDEX idx_attachments_disaster ON disaster_attachments (disaster_id);
