-- =====================================================================
-- V5: Rescue Team Coordination
-- Vehicles, equipment, missions, mission events, live tracking,
-- shift scheduling, plus inventory/enrichment columns.
-- Column names match JPA entities (Hibernate validate).
-- =====================================================================

-- ---------------------------------------------------------------------
-- Rescue vehicles
-- ---------------------------------------------------------------------
CREATE TABLE rescue_vehicles (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id              BIGINT,
    vehicle_type         VARCHAR(255),
    registration_number  VARCHAR(255),
    model                VARCHAR(255),
    capacity             INT NOT NULL DEFAULT 0,
    status               VARCHAR(255),
    latitude             DOUBLE PRECISION NOT NULL DEFAULT 0,
    longitude            DOUBLE PRECISION NOT NULL DEFAULT 0,
    fuel_level           INT NOT NULL DEFAULT 100,
    last_maintained_at   TIMESTAMP,
    next_maintenance_due TIMESTAMP,
    notes                VARCHAR(1000),
    version              BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_rescue_vehicles_team FOREIGN KEY (team_id) REFERENCES rescue_teams (id)
);

-- ---------------------------------------------------------------------
-- Rescue equipment (team inventory with quantity tracking)
-- ---------------------------------------------------------------------
CREATE TABLE rescue_equipment (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id                 BIGINT,
    name                    VARCHAR(255),
    equipment_type          VARCHAR(255),
    total_quantity          INT NOT NULL DEFAULT 0,
    available_quantity      INT NOT NULL DEFAULT 0,
    deployed_quantity       INT NOT NULL DEFAULT 0,
    in_maintenance_quantity INT NOT NULL DEFAULT 0,
    status                  VARCHAR(255),
    condition               VARCHAR(255),
    last_maintained_at      TIMESTAMP,
    next_maintenance_due    TIMESTAMP,
    notes                   VARCHAR(1000),
    version                 BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_rescue_equipment_team FOREIGN KEY (team_id) REFERENCES rescue_teams (id)
);

-- ---------------------------------------------------------------------
-- Rescue missions
-- ---------------------------------------------------------------------
CREATE TABLE rescue_missions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mission_code      VARCHAR(255),
    title             VARCHAR(255),
    mission_type      VARCHAR(255),
    description       VARCHAR(1000),
    team_id           BIGINT,
    disaster_id       BIGINT,
    status            VARCHAR(255),
    priority          VARCHAR(255),
    start_time        TIMESTAMP,
    end_time          TIMESTAMP,
    assigned_by       VARCHAR(255),
    instructions      VARCHAR(2000),
    created_by        VARCHAR(255),
    created_at        TIMESTAMP,
    completed_at      TIMESTAMP,
    cancelled_at      TIMESTAMP,
    cancelled_reason  VARCHAR(1000),
    version           BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_rescue_missions_team FOREIGN KEY (team_id) REFERENCES rescue_teams (id),
    CONSTRAINT fk_rescue_missions_disaster FOREIGN KEY (disaster_id) REFERENCES disasters (id)
);

-- ---------------------------------------------------------------------
-- Mission event history
-- ---------------------------------------------------------------------
CREATE TABLE mission_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mission_id   BIGINT,
    event_type   VARCHAR(255),
    message      VARCHAR(1000),
    performed_by VARCHAR(255),
    occurred_at  TIMESTAMP,
    CONSTRAINT fk_mission_events_mission FOREIGN KEY (mission_id) REFERENCES rescue_missions (id)
);

-- ---------------------------------------------------------------------
-- Team location updates (live tracking history)
-- ---------------------------------------------------------------------
CREATE TABLE team_location_updates (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id    BIGINT,
    latitude   DOUBLE PRECISION NOT NULL DEFAULT 0,
    longitude  DOUBLE PRECISION NOT NULL DEFAULT 0,
    heading    DOUBLE PRECISION NOT NULL DEFAULT 0,
    speed      DOUBLE PRECISION NOT NULL DEFAULT 0,
    accuracy   DOUBLE PRECISION NOT NULL DEFAULT 0,
    device_id  VARCHAR(255),
    timestamp  TIMESTAMP,
    CONSTRAINT fk_team_location_team FOREIGN KEY (team_id) REFERENCES rescue_teams (id)
);

-- ---------------------------------------------------------------------
-- Shift scheduling / duty roster
-- ---------------------------------------------------------------------
CREATE TABLE team_shifts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id      BIGINT,
    member_id    BIGINT,
    shift_type   VARCHAR(255),
    shift_status VARCHAR(255),
    shift_start  TIMESTAMP,
    shift_end    TIMESTAMP,
    notes        VARCHAR(1000),
    created_by   VARCHAR(255),
    version      BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_team_shifts_team FOREIGN KEY (team_id) REFERENCES rescue_teams (id),
    CONSTRAINT fk_team_shifts_member FOREIGN KEY (member_id) REFERENCES team_members (id)
);

-- ---------------------------------------------------------------------
-- Team member enrichment (leader flag, skills, certifications)
-- ---------------------------------------------------------------------
ALTER TABLE team_members ADD COLUMN is_leader       BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE team_members ADD COLUMN skills          VARCHAR(1000);
ALTER TABLE team_members ADD COLUMN certifications  VARCHAR(1000);
ALTER TABLE team_members ADD COLUMN joined_at       TIMESTAMP;

-- ---------------------------------------------------------------------
-- Rescue team enrichment
-- ---------------------------------------------------------------------
ALTER TABLE rescue_teams ADD COLUMN specialty             VARCHAR(255);
ALTER TABLE rescue_teams ADD COLUMN max_capacity          INT NOT NULL DEFAULT 0;
ALTER TABLE rescue_teams ADD COLUMN last_location_update_at TIMESTAMP;

-- ---------------------------------------------------------------------
-- Resource inventory enrichment (deployment / return / maintenance)
-- ---------------------------------------------------------------------
ALTER TABLE resources ADD COLUMN total_quantity          INT NOT NULL DEFAULT 0;
ALTER TABLE resources ADD COLUMN deployed_quantity       INT NOT NULL DEFAULT 0;
ALTER TABLE resources ADD COLUMN in_maintenance_quantity INT NOT NULL DEFAULT 0;
ALTER TABLE resources ADD COLUMN condition               VARCHAR(255);
ALTER TABLE resources ADD COLUMN last_maintained_at      TIMESTAMP;
ALTER TABLE resources ADD COLUMN maintenance_due_at      TIMESTAMP;
ALTER TABLE resources ADD COLUMN deployed_at             TIMESTAMP;
ALTER TABLE resources ADD COLUMN returned_at             TIMESTAMP;
ALTER TABLE resources ADD COLUMN assigned_mission_id     BIGINT;

-- ---------------------------------------------------------------------
-- Indexes for hot query paths
-- ---------------------------------------------------------------------
CREATE INDEX idx_rescue_vehicles_team  ON rescue_vehicles (team_id);
CREATE INDEX idx_rescue_vehicles_status ON rescue_vehicles (status);
CREATE INDEX idx_rescue_equipment_team ON rescue_equipment (team_id);
CREATE INDEX idx_rescue_equipment_status ON rescue_equipment (status);
CREATE INDEX idx_rescue_missions_team ON rescue_missions (team_id);
CREATE INDEX idx_rescue_missions_disaster ON rescue_missions (disaster_id);
CREATE INDEX idx_rescue_missions_status ON rescue_missions (status);
CREATE INDEX idx_mission_events_mission ON mission_events (mission_id);
CREATE INDEX idx_team_location_team ON team_location_updates (team_id, timestamp);
CREATE INDEX idx_team_shifts_team ON team_shifts (team_id);
CREATE INDEX idx_team_shifts_member ON team_shifts (member_id);
CREATE INDEX idx_team_shifts_time ON team_shifts (shift_start, shift_end);
CREATE INDEX idx_team_members_leader ON team_members (team_id, is_leader);
CREATE INDEX idx_resources_mission ON resources (assigned_mission_id);
