-- =====================================================================
-- V6: Mission asset tracking + resource movement audit trail
-- Links vehicles/equipment to missions and records every deploy/return/
-- maintenance operation for resource inventory.
-- Column names match JPA entities (Hibernate validate).
-- =====================================================================

-- ---------------------------------------------------------------------
-- Rescue vehicles: mission assignment
-- ---------------------------------------------------------------------
ALTER TABLE rescue_vehicles ADD COLUMN assigned_mission_id BIGINT;
ALTER TABLE rescue_vehicles ADD COLUMN deployed_at TIMESTAMP;
ALTER TABLE rescue_vehicles ADD COLUMN returned_at TIMESTAMP;
ALTER TABLE rescue_vehicles ADD CONSTRAINT fk_rescue_vehicles_mission
    FOREIGN KEY (assigned_mission_id) REFERENCES rescue_missions (id);

-- ---------------------------------------------------------------------
-- Rescue equipment: mission assignment
-- ---------------------------------------------------------------------
ALTER TABLE rescue_equipment ADD COLUMN assigned_mission_id BIGINT;
ALTER TABLE rescue_equipment ADD COLUMN deployed_at TIMESTAMP;
ALTER TABLE rescue_equipment ADD COLUMN returned_at TIMESTAMP;
ALTER TABLE rescue_equipment ADD CONSTRAINT fk_rescue_equipment_mission
    FOREIGN KEY (assigned_mission_id) REFERENCES rescue_missions (id);

-- ---------------------------------------------------------------------
-- Resource movement audit trail
-- ---------------------------------------------------------------------
CREATE TABLE resource_movements (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id           BIGINT,
    mission_id            BIGINT,
    movement_type         VARCHAR(255),
    quantity              INT NOT NULL DEFAULT 0,
    actor                 VARCHAR(255),
    notes                 VARCHAR(1000),
    available_after       INT NOT NULL DEFAULT 0,
    deployed_after        INT NOT NULL DEFAULT 0,
    in_maintenance_after  INT NOT NULL DEFAULT 0,
    occurred_at           TIMESTAMP,
    CONSTRAINT fk_resource_movements_resource FOREIGN KEY (resource_id) REFERENCES resources (id),
    CONSTRAINT fk_resource_movements_mission FOREIGN KEY (mission_id) REFERENCES rescue_missions (id)
);

-- ---------------------------------------------------------------------
-- Indexes for hot query paths
-- ---------------------------------------------------------------------
CREATE INDEX idx_rescue_vehicles_mission ON rescue_vehicles (assigned_mission_id);
CREATE INDEX idx_rescue_equipment_mission ON rescue_equipment (assigned_mission_id);
CREATE INDEX idx_resource_movements_resource ON resource_movements (resource_id);
CREATE INDEX idx_resource_movements_mission ON resource_movements (mission_id);
CREATE INDEX idx_resource_movements_type ON resource_movements (movement_type);
CREATE INDEX idx_resource_movements_time ON resource_movements (occurred_at);
